# Pushæ™‚ã¯CIã®ã¿ã€Mergeæ™‚ã¯CIãŠã‚ˆã³CDã‚’å®Ÿè¡Œã™ã‚‹GitHub Actionsã‚’ä½œã‚‹ï¼ˆå˜ä¸€ã®Workflowã§ï¼‰
# https://dev.classmethod.jp/articles/create-github-actions-that-run-ci-only-when-push-and-ci-and-cd-when-merging-in-a-single-workflow/

on:
  push:

env:
  REG_SUIT_CLIENT_ID: ${{ secrets.REG_SUIT_CLIENT_ID }}
  REG_SUIT_S3_BUCKET_NAME: ${{ secrets.REG_SUIT_S3_BUCKET_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version ğŸ”
        run: node --version

      - name: Checkout ğŸ›
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy env file ğŸ“
        run: cp .env.dist .env.local

      - name: Cache Next.js Dependency ğŸ·
        uses: actions/cache@v3
        id: cache_nextjs_dependency_id
        env:
          cache-name: cache-nextjs-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install Next.js Dependency ğŸ“¦
        if: ${{ steps.cache_nextjs_dependency_id.outputs.cache-hit != 'true' }}
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build Test ğŸ› 
        run: |
          yarn build
          yarn sitemap

      # https://www.pnkts.net/2021/10/14/chromium-chromedriver-japanese
      - name: Install Japanese fonts
        run: |
          sudo apt install fonts-ipafont fonts-ipaexfont

      # https://github.com/reg-viz/reg-suit#workaround-for-detached-head
      - name: Workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull

      - name: Visual Regression Test ğŸ–¼
        run: |
          yarn storycap
          yarn regression -v

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: integration
    steps:
      - name: Print Node.js version ğŸ”
        run: node --version

      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Copy env file ğŸ“
        run: cp .env.dist .env.local

      - name: Cache Next.js Dependency ğŸ·
        uses: actions/cache@v3
        id: cache_nextjs_dependency_id
        env:
          cache-name: cache-nextjs-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Generate Next.js ğŸ§‘ğŸ»â€ğŸ’»
        run: yarn export

      - name: Deploy to Firebase ğŸ”¥
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YURIKAGO_BLOG }}'
          channelId: live
          projectId: yurikago-blog
