# Pushæ™‚ã¯CIã®ã¿ã€Mergeæ™‚ã¯CIãŠã‚ˆã³CDã‚’å®Ÿè¡Œã™ã‚‹GitHub Actionsã‚’ä½œã‚‹ï¼ˆå˜ä¸€ã®Workflowã§ï¼‰
# https://dev.classmethod.jp/articles/create-github-actions-that-run-ci-only-when-push-and-ci-and-cd-when-merging-in-a-single-workflow/

on:
  push:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version ğŸ”
        run: node --version

      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Copy env file ğŸ“
        run: cp .env.dist .env.local

      - name: Cache Next.js Dependency ğŸ·
        uses: actions/cache@v3
        id: cache_nextjs_dependency_id
        env:
          cache-name: cache-nextjs-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install Next.js Dependency ğŸ“¦
        if: ${{ steps.cache_nextjs_dependency_id.outputs.cache-hit != 'true' }}
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build Test ğŸ› 
        run: |
          yarn build
          yarn sitemap

      - name: Install jq ğŸ“¦
        run: yarn add global jq

      # ã‚¯ãƒ©ã‚¤ã‚¢ãƒ³ãƒˆIDã¨S3ãƒã‚±ãƒƒãƒˆåã‚’ç’°å¢ƒå¤‰æ•°ã‹ã‚‰èª­ã¿è¾¼ã‚“ã§JSONã«è¨­å®šã™ã‚‹
      - name: Set reg-suit config ğŸ“
        run: |
          cat regconfig.json | jq '.plugins."reg-notify-github-plugin".clientId|="${{ secrets.REG_SUIT_CLIENT_ID }}"' > regconfig.json
          cat regconfig.json | jq '.plugins."reg-publish-s3-plugin".bucketName|="${{ secrets.REG_SUIT_S3_BUCKET_NAME }}"' > regconfig.json

      - name: Visual Regression Test ğŸ–¼
        run: |
          yarn storycap
          yarn regression -v

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs: integration
    steps:
      - name: Print Node.js version ğŸ”
        run: node --version

      - name: Checkout ğŸ›
        uses: actions/checkout@v3

      - name: Copy env file ğŸ“
        run: cp .env.dist .env.local

      - name: Cache Next.js Dependency ğŸ·
        uses: actions/cache@v3
        id: cache_nextjs_dependency_id
        env:
          cache-name: cache-nextjs-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Generate Next.js ğŸ§‘ğŸ»â€ğŸ’»
        run: yarn export

      - name: Deploy to Firebase ğŸ”¥
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YURIKAGO_BLOG }}'
          channelId: live
          projectId: yurikago-blog
